# example settings file
version: 1
port: 3000
pgdumpTestMode: true
jobs:
    # job name must match database name
    mydatabase:
        # cronmask must be wrapped in quotes, as the slashes can break YML
        cronmask: "*/10 * * * * *"
        preserve: 10
        args: 
          format: tar
        # optional s3 bucket target
        s3:
            bucket: my-bucket
            key: somekey
            secret: somesecret
