# example settings file
version: 1
port: 3000
pgdumpTestMode: true
jobs:
    # job name must match database name
    mydatabase:
        crondmask: "*/10 * * * * *"
        preserve: 10
        # optional s3 bucket target
        s3:
            bucket: my-bucket
            key: somekey
            secret: somesecret
